### ISSUE TITLE
Text overflow on menubar sides when resizing

### ISSUE THREAD

**Issue by frksteenhoff** [NationalMuseumofDenmark/official.frontend.component#23]
### Look when resizing
![image](https://user-images.githubusercontent.com/6978512/78218557-46e14c80-74be-11ea-97f4-0c296aa4ba2d.png)

**Comment by kparkov** [comment]
The menu should be placed inside a `<Section fluid>` so it uses up 100% screen width.

This is no longer considered a bug.
